# Generated by Django 5.0.2 on 2024-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userFiles',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
