# Generated by Django 5.0.6 on 2024-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
