# Generated by Django 5.0.6 on 2024-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0002_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
