# Generated by Django 5.0.6 on 2024-07-25 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0003_remove_specification_delivery_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ajustes_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PRODUZINDO', 'Produzindo'), ('EM_APROVACAO', 'Em aprovação'), ('ENTREGUE', 'Entregue'), ('EM_AJUSTE', 'Em ajuste')], default='A_FAZER', max_length=100),
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='ajustes_files/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajuste', to='bloomy.order')),
            ],
        ),
    ]
