# Generated by Django 5.0.2 on 2024-06-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0003_package_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_usages', models.IntegerField(default=0)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='bloomy.subscription')),
            ],
        ),
    ]
