# Generated by Django 5.0.2 on 2024-06-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0004_usage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
