# Generated by Django 5.0.6 on 2024-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0004_order_ajustes_counter_alter_order_status_ajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PRODUZINDO', 'Produzindo'), ('EM_APROVACAO', 'Em aprovação'), ('ENTREGUE', 'Entregue'), ('EM_AJUSTE', 'Em ajuste')], default='PRODUZINDO', max_length=100),
        ),
    ]
