# Generated by Django 5.0.6 on 2024-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userFiles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
