# Generated by Django 5.0.6 on 2024-06-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0005_delete_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orderUploads/')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderFiles',
            field=models.ManyToManyField(related_name='orders', to='bloomy.file'),
        ),
    ]
