# Generated by Django 5.0.6 on 2024-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PRODUZINDO', 'Produzindo'), ('EM_APROVACAO', 'Em aprovação'), ('ENTREGUE', 'Entregue'), ('EM_AJUSTE', 'Em ajuste'), ('CANCELADO', 'Cancelado')], default='PRODUZINDO', max_length=100),
        ),
    ]
