# Generated by Django 5.0.6 on 2024-06-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0006_file_order_orderfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderFiles',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='order',
            name='orderFiles',
            field=models.FileField(blank=True, null=True, upload_to='order_files/'),
        ),
    ]
