# Generated by Django 5.0.6 on 2024-07-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuste',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='bloomy.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bloomy.order'),
        ),
    ]
