# Generated by Django 5.0.6 on 2024-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0007_alter_ajuste_order_alter_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_id',
            field=models.CharField(default=0, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
