# Generated by Django 5.0.6 on 2024-06-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0007_remove_order_orderfiles_delete_file_order_orderfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
    ]
