# Generated by Django 5.0.6 on 2024-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0008_order_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_peca_file',
            field=models.FileField(blank=True, null=True, upload_to='for_peca_order_files/'),
        ),
        migrations.AddField(
            model_name='order',
            name='prefered_colors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
