# Generated by Django 5.0.6 on 2024-06-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0008_remove_order_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A_FAZER', 'A fazer'), ('EM_PRODUCAO', 'Em produçao'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='A_FAZER', max_length=100),
        ),
    ]
