# Generated by Django 5.0.6 on 2024-06-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='comment',
        ),
        migrations.AddField(
            model_name='delivery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_files/'),
        ),
    ]
