# Generated by Django 5.0.6 on 2024-08-14 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomy', '0009_order_for_peca_file_order_prefered_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='for_peca_file',
            field=models.FileField(blank=True, null=True, upload_to='for_peca_files/'),
        ),
    ]
